# Generated by Django 2.0.2 on 2018-04-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='update_user',
        ),
    ]
