# Generated by Django 2.0.2 on 2018-04-10 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_taxoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsididaryTaxPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Registration Name')),
                ('address', models.TextField()),
                ('trade_name', models.CharField(max_length=150, verbose_name='Trade Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tin', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='JTB TIN')),
                ('company_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20, verbose_name='Company Size')),
                ('ownership_type', models.CharField(choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Trusteeship', 'Trusteeship'), ('Companies Limited By Guarantee', 'Companies Limited By Guarantee'), ('Federal MDAs', 'Federal MDAs'), ('State MDAs', 'State MDAs'), ('Foreign/Non-resident Companies', 'Foreign/Non-resident Companies'), ('Partnership', 'Partnership'), ('Private Unlimited Company', 'Private Unlimited Company'), ('Sole Proprietorship', 'Sole Proprietorship')], max_length=75, verbose_name='Organization Type')),
                ('reg_status', models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=20, verbose_name='Registration Status')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='CAC Registration Date')),
                ('start_date', models.DateField(verbose_name='Business Start Date')),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Registration Number')),
                ('line_of_business', models.CharField(max_length=75, verbose_name='Line of Business')),
                ('sector', models.CharField(max_length=75, verbose_name='Sector')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact Name')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_creater', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_company', to='dashboard.CorporateTaxPayer')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subsidiary Company',
            },
        ),
    ]
