# Generated by Django 2.0.2 on 2018-04-10 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_subsididarytaxpayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubsididaryTaxPayer',
            new_name='SubsidiaryTaxPayer',
        ),
    ]
