# Generated by Django 2.0.2 on 2018-04-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_corporateshareholder_individualshareholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateshareholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_company', to='dashboard.CorporateTaxPayer'),
        ),
        migrations.AddField(
            model_name='individualshareholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_company', to='dashboard.CorporateTaxPayer'),
        ),
    ]
