# Generated by Django 2.0.2 on 2018-04-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180411_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualshareholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='dashboard.CorporateTaxPayer'),
        ),
    ]
