# Generated by Django 2.0.2 on 2018-04-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180411_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetaxpayer',
            name='tax_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_tax_office', to='dashboard.TaxOffice'),
        ),
        migrations.AddField(
            model_name='individualtaxpayer',
            name='tax_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_tax_office', to='dashboard.TaxOffice'),
        ),
    ]
