# Generated by Django 2.0.2 on 2018-04-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180411_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='f1',
            field=models.TextField(verbose_name='Finger #1'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f10',
            field=models.TextField(verbose_name='Finger #10'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f2',
            field=models.TextField(verbose_name='Finger #2'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f3',
            field=models.TextField(verbose_name='Finger #3'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f4',
            field=models.TextField(verbose_name='Finger #4'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f5',
            field=models.TextField(verbose_name='Finger #5'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f6',
            field=models.TextField(verbose_name='Finger #6'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f7',
            field=models.TextField(verbose_name='Finger #7'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f8',
            field=models.TextField(verbose_name='Finger #8'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f9',
            field=models.TextField(verbose_name='Finger #9'),
        ),
    ]
