# Generated by Django 2.0.2 on 2018-04-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180412_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='f10',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #10'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f4',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #4'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f5',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #5'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f6',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #6'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f7',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #7'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f8',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #8'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='f9',
            field=models.TextField(blank=True, null=True, verbose_name='Finger #9'),
        ),
    ]
