# Generated by Django 2.0.2 on 2018-04-15 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20180413_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Agency Name')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registration Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_creater', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='corporatetaxpayer',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_agency', to='dashboard.Agency'),
        ),
        migrations.AddField(
            model_name='individualtaxpayer',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_agency', to='dashboard.Agency'),
        ),
    ]
