# Generated by Django 2.0.2 on 2018-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180415_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='individualtaxpayer',
            options={'verbose_name': 'Individual Tax Payer'},
        ),
        migrations.AddField(
            model_name='agency',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='agency',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
