# Generated by Django 2.0.2 on 2018-04-15 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20180415_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bvn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=75, verbose_name='Surname')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('other_name', models.CharField(max_length=75, null=True, verbose_name='Other Name')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, verbose_name='Marital Status')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('bvn', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='BVN')),
                ('tax_payer_company', models.CharField(max_length=150, null=True, verbose_name='Company')),
                ('occupation', models.CharField(max_length=75, verbose_name='Occupation')),
                ('employment_status', models.CharField(choices=[('Unemployed', 'Unemployed'), ('Self Employed', 'Self Employed'), ('Employed', 'Employed')], max_length=20, verbose_name='Employment Status')),
                ('residential_address', models.TextField()),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bvn_agency', to='dashboard.Agency')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bvn_creater', to=settings.AUTH_USER_MODEL)),
                ('lga_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bvn_lga', to='dashboard.Lga')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bvn_nationality', to='dashboard.Country')),
                ('state_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bvn_state', to='dashboard.State')),
                ('tax_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bvn_tax_office', to='dashboard.TaxOffice')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bvn_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BVN Records',
            },
        ),
    ]
