# Generated by Django 2.0.2 on 2018-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_bvn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bvn',
            options={'verbose_name': 'BVN Record', 'verbose_name_plural': 'BVN Records'},
        ),
        migrations.AddField(
            model_name='bvn',
            name='generated',
            field=models.NullBooleanField(default=False),
        ),
    ]
