# Generated by Django 2.0.2 on 2018-04-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180416_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvn',
            name='bvn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='BVN'),
        ),
    ]
